main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

trailer_show:
  method: 'get'
  path: 'trailer/{id}'
  controller: App\Controller\HomeController
  action: show